// SPDX-FileCopyrightText: 2026 movblock <admin@movblock.mov>
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.client.render.flywheel;

import com.hbm.blocks.ModBlockEntities;
import com.hbm.blocks.rail.RailStandardSwitch;
import dev.engine_room.flywheel.lib.visualization.SimpleBlockEntityVisualizer;

public final class MachineVisuals {
    private MachineVisuals() {}

    public static void register() {
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FUSION_TORUS_STRUCT.get())
                .factory(FusionTorusStructPreviewVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ICF_STRUCT.get())
                .factory(ICFStructPreviewVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.WATZ_STRUCT.get())
                .factory(WatzStructPreviewVisual::new)
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_SLAGTAP.get())
                .factory(FoundryOutletVisual::new)
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MULTI_CORE.get())
                .factory(MultiblockStructPreviewVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SOYUZ_STRUCT.get())
                .factory(SoyuzStructPreviewVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_CONSOLE.get())
                .factory(RBMKConsoleVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_DISPLAY.get())
                .factory(RBMKDisplayVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_OUTLET.get())
                .factory(FoundryOutletVisual::new)
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.REFUELER.get())
                .factory(RefuelerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ELECTROLYSER.get())
                .factory(ElectrolyserVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.STRAND_CASTER.get())
                .factory(StrandCasterVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ROTARY_FURNACE.get())
                .factory(RotaryFurnaceVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ARC_FURNACE_LARGE.get())
                .factory(ArcFurnaceVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MACHINE_PUMPJACK.get())
                .factory(PumpjackVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.BATTERY_REDD.get())
                .factory(BatteryREDDVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FLUID_TANK.get())
                .factory(FluidTankVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FLUID_BARREL.get())
                .factory(BarrelVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.TURRET_TAUON.get())
                .factory(TurretTauonVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.TURRET_MAXWELL.get())
                .factory(TurretMaxwellVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.BIGASSTANK.get())
                .factory(BigAssTankVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.NTM_BOBBLEHEAD.get())
                .factory(BobbleVisual::new)
                .skipVanillaRender(be -> !BobbleVisual.vanillaNeeded(be))
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.HEPHAESTUS.get())
                .factory(HephaestusVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.IND_TURBINE.get())
                .factory(IndustrialTurbineVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.INTAKE.get())
                .factory(IntakeVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LPW2.get())
                .factory(LPW2Visual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LANTERN.get())
                .factory(LanternVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LANTERN_BEHEMOTH.get())
                .factory(LanternBehemothVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.INDUSTRIAL_TURBINE.get())
                .factory(LargeTurbineVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LAUNCH1.get())
                .factory(LaunchPadVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LAUNCHPAD_LARGE.get())
                .factory(LaunchPadLargeVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LAUNCHPAD_RUSTED.get())
                .factory(LaunchPadRustedVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LARGE_LAUNCH_TABLE.get())
                .factory(LaunchTableVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LIQUEFACTOR.get())
                .factory(LiquefactorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.NTM_LOOT.get())
                .factory(LootVisual::new)
                .skipVanillaRender(be -> !LootVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MASS_STORAGE.get())
                .factory(MassStorageVisual::new)
                .skipVanillaRender(be -> !MassStorageVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MICROWAVE.get())
                .factory(MicrowaveVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MISSILE_ASSEMBLY.get())
                .factory(MissileAssemblyVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MIXER.get())
                .factory(MixerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ORE_SLOPPER.get())
                .factory(OreSlopperVisual::new)
                .skipVanillaRender(be -> !OreSlopperVisual.vanillaNeeded(be))
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FEL.get())
                .factory(FELVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.BATTERY_SOCKET.get())
                .factory(BatterySocketVisual::new)
                .skipVanillaRender(be -> !BatterySocketVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ASSEMBLYFACTORY.get())
                .factory(AssemblyFactoryVisual::new)
                .skipVanillaRender(be -> !AssemblyFactoryVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CORE_CORE.get())
                .factory(CoreVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FUSION_PLASMA_FORGE.get())
                .factory(FusionPlasmaForgeVisual::new)
                .skipVanillaRender(be -> !FusionPlasmaForgeVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MINING_LASER.get())
                .factory(LaserMinerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FORCEFIELD.get())
                .factory(ForceFieldVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.EXPOSURE_CHAMBER.get())
                .factory(ExposureChamberVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MACHINE_REACTOR_BREEDING.get())
                .factory(BreederVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.REACTOR_RESEARCH.get())
                .factory(SmallReactorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.EMITTER.get())
                .factory(EmitterVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.NUKE_FSTBMB.get())
                .factory(NukeFstbmbVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_GRAPH.get())
                .factory(RBMKGraphVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ORBUS.get())
                .factory(OrbusVisual::new)
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.AMMO_PRESS.get())
                .factory(AmmoPressVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ANNIHILATOR.get())
                .factory(AnnihilatorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SUPERCOMPUTER.get())
                .factory(SuperComputerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.TAPE_DRIVE.get())
                .factory(TapeDriveVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ASHPIT.get())
                .factory(AshpitVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ASSEMBLYMACHINE.get())
                .factory(AssemblyMachineVisual::new)
                .skipVanillaRender(be -> !AssemblyMachineVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.AUTOSAW.get())
                .factory(AutosawVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.BLAST_DOOR.get())
                .factory(BlastDoorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CARGO_ELEVATOR.get())
                .factory(CargoElevatorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.NTM_CHARGER.get())
                .factory(ChargerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CHEMICALFACTORY.get())
                .factory(ChemicalFactoryVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CHEMICALPLANT.get())
                .factory(ChemicalPlantVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ROCK_MILL.get())
                .factory(RockMillVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CHUNGUS.get())
                .factory(ChungusVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.COMBUSTION_ENGINE.get())
                .factory(CombustionEngineVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SMALL_LAUNCHER.get())
                .factory(CompactLauncherVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.COMPRESSOR.get())
                .factory(CompressorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.COMPRESSOR_COMPACT.get())
                .factory(CompressorCompactVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CONDENSER_POWERED.get())
                .factory(CondenserPoweredVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CONVEYOR_PRESS.get())
                .factory(ConveyorPressVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ACIDOMATIC.get())
                .factory(CrystallizerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PA_BEAMLINE.get())
                .factory(PABeamlineVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PUREX.get())
                .factory(PUREXVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PRECASS.get())
                .factory(PrecAssVisual::new)
                .skipVanillaRender(be -> !PrecAssVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.STEAM_PUMP.get())
                .factory(PumpVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PIOE_ANCHOR.get())
                .factory(PipeAnchorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_ROD.get())
                .factory(RBMKFuelRodVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_ROD_REASIM.get())
                .factory(RBMKFuelRodVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_CONTROL.get())
                .factory(RBMKControlRodVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_CONTROL_AUTO.get())
                .factory(RBMKControlRodVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_GAUGE.get())
                .factory(RBMKGaugeVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_NUMITRON.get())
                .factory(RBMKNumitronVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_INDICATOR.get())
                .factory(RBMKIndicatorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_LEVER.get())
                .factory(RBMKLeverVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_KEYPAD.get())
                .factory(RBMKKeyPadVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_AUTOLOADER.get())
                .factory(RBMKAutoloaderVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PILE_LOADER.get())
                .factory(PileLoaderVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PILE_VENT.get())
                .factory(PileVentVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PILE_CONTROL.get())
                .factory(PileControlVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PISTON_INSERTER.get())
                .factory(PistonInserterVisual::new)
                .skipVanillaRender(be -> !PistonInserterVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RBMK_CRANE_CONSOLE.get())
                .factory(RBMKCraneConsoleVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PYROOVEN.get())
                .factory(PyroOvenVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ELECTRIC_PUMP.get())
                .factory(PumpVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.NTM_PLUSHIE.get())
                .factory(PlushieVisual::new)
                .skipVanillaRender(be -> !PlushieVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CYCLOTRON.get())
                .factory(CyclotronVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.DEMON_LAMP.get())
                .factory(DemonLampVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.DIESEL_GENERATOR.get())
                .factory(DieselVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.EXCAVATOR.get())
                .factory(ExcavatorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FENSU.get())
                .factory(FENSUVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FAN.get())
                .factory(FanVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FILE_CABINET.get())
                .factory(FileCabinetVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FIREBOX.get())
                .factory(FireboxVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FLOODLIGHT.get())
                .factory(FloodlightVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.COMBINATION_OVEN.get())
                .factory(FurnaceCombinationVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FURNACE_IRON.get())
                .factory(FurnaceIronVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FURNACE_STEEL.get())
                .factory(FurnaceSteelVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FUSION_KLYSTRON.get())
                .factory(FusionKlystronVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FUSION_KLYSTRON_CREATIVE.get())
                .factory(FusionKlystronCreativeVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FUSION_MHDT.get())
                .factory(FusionMHDTVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FUSION_TORUS.get())
                .factory(FusionTorusVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.HEAT_BOILER.get())
                .factory(HeatBoilerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.HEATING_OVEN.get())
                .factory(HeaterOvenVisual::new)
                .apply();

        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RAIL.get())
                .factory(
                        (ctx, be, partialTick) ->
                                be.getBlockState().getBlock() instanceof RailStandardSwitch
                                        ? new RailVisual(ctx, be, partialTick)
                                        : null)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RADGEN.get())
                .factory(RadGenVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RADAR.get())
                .factory(RadarVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RADAR_LARGE.get())
                .factory(RadarLargeVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SATLINK.get())
                .factory(SatLinkVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.RADAR_SCREEN.get())
                .factory(RadarScreenVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.MACHINE_TURBOFAN.get())
                .factory(TurbofanVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.STEAM_ENGINE.get())
                .factory(SteamEngineVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SOLARMIRROR.get())
                .factory(SolarMirrorVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SOLARBOILER.get())
                .factory(SolarBoilerVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.TURRET_HOWARD_DAMAGED.get())
                .factory(TurretHowardDamagedVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SOYUZ_LAUNCHER.get())
                .factory(SoyuzLauncherVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.LAUNCHPAD_SOYUZ.get())
                .factory(LaunchpadSoyuzVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SOLIDIFIER.get())
                .factory(SolidifierVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.THRESHER.get())
                .factory(ThresherVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SAWMILL.get())
                .factory(SawmillVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.STIRLING.get())
                .factory(StirlingVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.NTM_SNOWGLOBE.get())
                .factory(SnowglobeVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CRUCIBLE.get())
                .factory(CrucibleVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_MOLD.get())
                .factory(FoundryVisual::new)
                .skipVanillaRender(be -> !FoundryVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_BASIN.get())
                .factory(FoundryVisual::new)
                .skipVanillaRender(be -> !FoundryVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_CHANNEL.get())
                .factory(FoundryChannelVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PYLON_REDWIRE.get())
                .factory(PylonWiresVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PYLON_MEDIUM.get())
                .factory(PylonWiresVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CONNECTOR_REDWIRE.get())
                .factory(PylonWiresVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CONNECTOR_REDWIRE_SUPER.get())
                .factory(PylonWiresVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PYLON_LARGE.get())
                .factory(PylonWiresVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.SUBSTATION.get())
                .factory(PylonWiresVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_TANK.get())
                .factory(FoundryTankVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.FOUNDRY_SLAG.get())
                .factory(SlagVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.TESLA_COIL.get())
                .factory(TeslaVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CORE_EMITTER.get())
                .factory(CoreComponentVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CORE_INJECTOR.get())
                .factory(CoreComponentVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CORE_STABILIZER.get())
                .factory(CoreComponentVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.CRASHED_BALEFIRE.get())
                .factory(CrashedBombVisual::new)
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.PRESS.get())
                .factory(PressVisual::new)
                .skipVanillaRender(be -> !PressVisual.vanillaNeeded(be))
                .apply();
        SimpleBlockEntityVisualizer.builder(ModBlockEntities.ELECTRIC_PRESS.get())
                .factory(ElectricPressVisual::new)
                .skipVanillaRender(be -> !ElectricPressVisual.vanillaNeeded(be))
                .apply();
    }
}
