// SPDX-FileCopyrightText: 2026 movblock <admin@movblock.mov>
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.packet;

import com.hbm.packet.synthetic.PingPayload;
import com.hbm.packet.toclient.*;
import com.hbm.packet.toserver.*;
import com.hbm.platform.Services;

public final class PacketDispatcher {

    private PacketDispatcher() {}

    public static void register() {
        Services.NETWORK.registerClientbound(
                BlobPayload.TYPE,
                BlobPayload.STREAM_CODEC,
                BlobPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                SyncRequestPayload.TYPE,
                SyncRequestPayload.STREAM_CODEC,
                SyncRequestPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                UnitPayload.TYPE,
                UnitPayload.STREAM_CODEC,
                UnitPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PingPayload.S2C_TYPE,
                PingPayload.S2C_STREAM_CODEC,
                PingPayload::handleClient,
                PayloadHandlerThread.NETWORK);
        Services.NETWORK.registerClientbound(
                FluidPipeTintPayload.TYPE,
                FluidPipeTintPayload.STREAM_CODEC,
                FluidPipeTintPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                FluidPipeTintBulkPayload.TYPE,
                FluidPipeTintBulkPayload.STREAM_CODEC,
                FluidPipeTintBulkPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                RBMKDiagPayload.TYPE,
                RBMKDiagPayload.STREAM_CODEC,
                RBMKDiagPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                RadVisSnapshotPayload.TYPE,
                RadVisSnapshotPayload.STREAM_CODEC,
                RadVisSnapshotPayload::handle,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerPreJoinSync(
                FluidPropertySyncPayload.TYPE,
                FluidPropertySyncPayload.STREAM_CODEC,
                FluidPropertySyncPayload::apply,
                FluidPropertySyncPayload::of);
        Services.NETWORK.registerPreJoinSync(
                BlueprintPoolSyncPayload.TYPE,
                BlueprintPoolSyncPayload.STREAM_CODEC,
                BlueprintPoolSyncPayload::apply,
                BlueprintPoolSyncPayload::of);
        Services.NETWORK.registerPreJoinSync(
                OreGenerationSyncPayload.TYPE,
                OreGenerationSyncPayload.STREAM_CODEC,
                OreGenerationSyncPayload::apply,
                OreGenerationSyncPayload::of);
        Services.SERVER.onServerTickPre(FluidPropertySyncPayload::resendIfPending);
        Services.NETWORK.registerDatapackSync(
                RecipeSyncPayload.TYPE,
                RecipeSyncPayload.STREAM_CODEC,
                RecipeSyncPayload::apply,
                RecipeSyncPayload::of);
        Services.NETWORK.registerDatapackSync(
                QMAWSyncPayload.TYPE,
                QMAWSyncPayload.STREAM_CODEC,
                QMAWSyncPayload::apply,
                QMAWSyncPayload::of);
        Services.SERVER.onServerStopping(server -> com.hbm.qmaw.QMAWCatalog.clearServer());
        Services.NETWORK.registerClientbound(
                HbmPlayerSyncPayload.TYPE,
                HbmPlayerSyncPayload.STREAM_CODEC,
                HbmPlayerSyncPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                ImpactSyncPayload.TYPE,
                ImpactSyncPayload.STREAM_CODEC,
                ImpactSyncPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PollutionSyncPayload.TYPE,
                PollutionSyncPayload.STREAM_CODEC,
                PollutionSyncPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PlayerPropsPayload.TYPE,
                PlayerPropsPayload.STREAM_CODEC,
                PlayerPropsPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PlayerAppearancePayload.TYPE,
                PlayerAppearancePayload.STREAM_CODEC,
                PlayerAppearancePayload::handle,
                PayloadHandlerThread.MAIN);
        Services.SERVER.onStartTracking(PlayerAppearancePayload::sendInitial);
        Services.NETWORK.registerClientbound(
                EffectNTPayload.TYPE,
                EffectNTPayload.STREAM_CODEC,
                EffectNTPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                GasFlamePayload.TYPE,
                GasFlamePayload.STREAM_CODEC,
                GasFlamePayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                JetpackParticlePayload.TYPE,
                JetpackParticlePayload.STREAM_CODEC,
                JetpackParticlePayload::handle,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerClientbound(
                OcclusionRefreshPayload.TYPE,
                OcclusionRefreshPayload.STREAM_CODEC,
                OcclusionRefreshPayload::handle,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerClientbound(
                FallingMultiblockPayload.TYPE,
                FallingMultiblockPayload.STREAM_CODEC,
                FallingMultiblockPayload::handleClient,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerClientbound(
                HbmAnimationPayload.TYPE,
                HbmAnimationPayload.STREAM_CODEC,
                HbmAnimationPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                GunSoundPayload.TYPE,
                GunSoundPayload.STREAM_CODEC,
                GunSoundPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                GrenadeAnimationPayload.TYPE,
                GrenadeAnimationPayload.STREAM_CODEC,
                GrenadeAnimationPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                MuzzleFlashPayload.TYPE,
                MuzzleFlashPayload.STREAM_CODEC,
                MuzzleFlashPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                TeslaArcPayload.TYPE,
                TeslaArcPayload.STREAM_CODEC,
                TeslaArcPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                GlyphidPathPayload.TYPE,
                GlyphidPathPayload.STREAM_CODEC,
                GlyphidPathPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                CasingEjectPayload.TYPE,
                CasingEjectPayload.STREAM_CODEC,
                CasingEjectPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                GunCasingEjectPayload.TYPE,
                GunCasingEjectPayload.STREAM_CODEC,
                GunCasingEjectPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PlasmaBlastPayload.TYPE,
                PlasmaBlastPayload.STREAM_CODEC,
                PlasmaBlastPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                ExplosionSmallPayload.TYPE,
                ExplosionSmallPayload.STREAM_CODEC,
                ExplosionSmallPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                HazePayload.TYPE,
                HazePayload.STREAM_CODEC,
                HazePayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                ExplosionStandardPayload.TYPE,
                ExplosionStandardPayload.STREAM_CODEC,
                ExplosionStandardPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                SmokeShockPayload.TYPE,
                SmokeShockPayload.STREAM_CODEC,
                SmokeShockPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                MukePayload.TYPE,
                MukePayload.STREAM_CODEC,
                MukePayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                AmatFlashPayload.TYPE,
                AmatFlashPayload.STREAM_CODEC,
                AmatFlashPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                RbmkJetPayload.TYPE,
                RbmkJetPayload.STREAM_CODEC,
                RbmkJetPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                BlackPowderPayload.TYPE,
                BlackPowderPayload.STREAM_CODEC,
                BlackPowderPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                SparkBurstPayload.TYPE,
                SparkBurstPayload.STREAM_CODEC,
                SparkBurstPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                DebugParticlePayload.TYPE,
                DebugParticlePayload.STREAM_CODEC,
                DebugParticlePayload::handleClient,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerClientbound(
                AshesPayload.TYPE,
                AshesPayload.STREAM_CODEC,
                AshesPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                VomitPayload.TYPE,
                VomitPayload.STREAM_CODEC,
                VomitPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                SweatPayload.TYPE,
                SweatPayload.STREAM_CODEC,
                SweatPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                ProperJoltPayload.TYPE,
                ProperJoltPayload.STREAM_CODEC,
                ProperJoltPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                SkeletonPayload.TYPE,
                SkeletonPayload.STREAM_CODEC,
                SkeletonPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                GibletPayload.TYPE,
                GibletPayload.STREAM_CODEC,
                GibletPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                BlockDustBurstPayload.TYPE,
                BlockDustBurstPayload.STREAM_CODEC,
                BlockDustBurstPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                BlockDestroyPayload.TYPE,
                BlockDestroyPayload.STREAM_CODEC,
                BlockDestroyPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PwrPrintPayload.TYPE,
                PwrPrintPayload.STREAM_CODEC,
                PwrPrintPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                MarkerPayload.TYPE,
                MarkerPayload.STREAM_CODEC,
                MarkerPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PneumoAccessSyncPayload.TYPE,
                PneumoAccessSyncPayload.STREAM_CODEC,
                PneumoAccessSyncPayload::handleClient,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                PlayerInformPayload.TYPE,
                PlayerInformPayload.STREAM_CODEC,
                PlayerInformPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerClientbound(
                OreDensityPayload.TYPE,
                OreDensityPayload.STREAM_CODEC,
                OreDensityPayload::handle,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerServerbound(
                PingPayload.C2S_TYPE,
                PingPayload.C2S_STREAM_CODEC,
                PingPayload::handleServer,
                PayloadHandlerThread.MAIN);

        Services.NETWORK.registerServerbound(
                NbtControlPayload.TYPE,
                NbtControlPayload.STREAM_CODEC,
                NbtControlPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                FluidPipeTintRequestPayload.TYPE,
                FluidPipeTintRequestPayload.STREAM_CODEC,
                FluidPipeTintRequestPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                RBMKDiagRequestPayload.TYPE,
                RBMKDiagRequestPayload.STREAM_CODEC,
                RBMKDiagRequestPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                RadVisWatchPayload.TYPE,
                RadVisWatchPayload.STREAM_CODEC,
                RadVisWatchPayload::handle,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                FluidIdControlPayload.TYPE,
                FluidIdControlPayload.STREAM_CODEC,
                FluidIdControlPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                ToolPresetPayload.TYPE,
                ToolPresetPayload.STREAM_CODEC,
                ToolPresetPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                DesignatorCoordPayload.TYPE,
                DesignatorCoordPayload.STREAM_CODEC,
                DesignatorCoordPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                ItemControlPayload.TYPE,
                ItemControlPayload.STREAM_CODEC,
                ItemControlPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                RTTYPagerControlPayload.TYPE,
                RTTYPagerControlPayload.STREAM_CODEC,
                RTTYPagerControlPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                AnvilCraftPayload.TYPE,
                AnvilCraftPayload.STREAM_CODEC,
                AnvilCraftPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                BobmazonPurchasePayload.TYPE,
                BobmazonPurchasePayload.STREAM_CODEC,
                BobmazonPurchasePayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                PneumoAccessInputPayload.TYPE,
                PneumoAccessInputPayload.STREAM_CODEC,
                PneumoAccessInputPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                CraneKeyPayload.TYPE,
                CraneKeyPayload.STREAM_CODEC,
                CraneKeyPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                ToolKeyPayload.TYPE,
                ToolKeyPayload.STREAM_CODEC,
                ToolKeyPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                KeybindPayload.TYPE,
                KeybindPayload.STREAM_CODEC,
                KeybindPayload::handleServer,
                PayloadHandlerThread.MAIN);
        Services.NETWORK.registerServerbound(
                CrateOpenHeldPayload.TYPE,
                CrateOpenHeldPayload.STREAM_CODEC,
                CrateOpenHeldPayload::handleServer,
                PayloadHandlerThread.MAIN);
    }
}
