// SPDX-FileCopyrightText: 2026 movblock <admin@movblock.mov>
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.items.machine;

import com.hbm.items.ModDataComponents;
import com.hbm.items.ModItems;
import com.hbm.util.BobMathUtil;
import com.hbm.util.RTGUtil;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.function.Consumer;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.component.TooltipDisplay;
import net.minecraft.world.level.Level;
import org.jspecify.annotations.Nullable;

public class ItemRTGPellet extends Item {

    public static final List<ItemRTGPellet> pelletList = new ArrayList<>();
    private static final String[] FACTS =
            new String[] {
                "One gram of Pu-238 costs $8,000.",
                "One gram of Pu-238 produces just under half a Watt of decay heat.",
                "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
                "Pu-238's half life is 87.7 years.",
                "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
                "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
                "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
                "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
                "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
                "Thorium reactors are really uranium reactors that convert thorium into U-233.",
                "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
                "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
                "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
                "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
                "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
                "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
            };
    private final short heat;
    private boolean doesDecay = false;
    private @Nullable DepletedRTGMaterial decayMat = null;
    private long halflife = 0;
    private long lifespan = 0;

    public ItemRTGPellet(Properties props, int heatIn) {
        super(props);
        this.heat = (short) heatIn;
        pelletList.add(this);
    }

    public static ItemStack handleDecay(ItemStack stack, ItemRTGPellet instance) {
        if (instance.doesDecay && RTGUtil.RTG_DECAY) {
            if (instance.getLifespan(stack) <= 0) {
                ItemStack decayed = instance.getDecayItem();
                if (decayed != null) return decayed;
            } else {
                instance.decay(stack);
            }
        }
        return stack;
    }

    public static short getScaledPower(ItemRTGPellet fuel, ItemStack stack) {
        if (fuel.lifespan <= 0) return fuel.heat;
        return (short)
                Math.ceil(fuel.heat * ((double) fuel.getLifespan(stack) / (double) fuel.lifespan));
    }

    public ItemRTGPellet setDecays(DepletedRTGMaterial mat, long halflife, double halflifeCount) {
        this.doesDecay = true;
        this.decayMat = mat;
        this.halflife = halflife;
        this.lifespan = (long) (halflife * halflifeCount);
        return this;
    }

    public long getMaxLifespan() {
        return lifespan;
    }

    public long getHalfLife() {
        return halflife;
    }

    public short getHeat() {
        return heat;
    }

    public boolean getDoesDecay() {
        return doesDecay;
    }

    public @Nullable DepletedRTGMaterial getDecayMat() {
        return decayMat;
    }

    public @Nullable ItemStack getDecayItem() {
        return decayMat == null ? null : new ItemStack(ModItems.getDepleted(decayMat));
    }

    public void decay(ItemStack stack) {
        if (!doesDecay) return;
        stack.set(ModDataComponents.PELLET_DEPLETION.get(), getLifespan(stack) - 1);
    }

    public long getLifespan(ItemStack stack) {
        Long rem = stack.get(ModDataComponents.PELLET_DEPLETION.get());
        return rem != null ? rem : lifespan;
    }

    @Override
    public boolean isBarVisible(ItemStack stack) {
        return doesDecay && getLifespan(stack) != lifespan;
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        if (lifespan <= 0) return 0;
        return Math.round(13.0F * (float) ((double) getLifespan(stack) / (double) lifespan));
    }

    @Override
    public int getBarColor(ItemStack stack) {
        return 0x33FF33;
    }

    @Override
    public void appendHoverText(
            ItemStack stack,
            Item.TooltipContext context,
            TooltipDisplay display,
            Consumer<Component> adder,
            TooltipFlag flag) {
        adder.accept(Component.translatable(getDescriptionId() + ".desc"));
        short shown = SCALED() ? getScaledPower(this, stack) : heat;
        adder.accept(Component.translatable("desc.item.rtgHeat", shown));
        if (!doesDecay) return;

        ItemStack decayItem = getDecayItem();
        if (decayItem != null)
            adder.accept(Component.translatable("desc.item.rtgDecay", decayItem.getHoverName()));
        long max = lifespan;
        long rem = getLifespan(stack);
        adder.accept(
                Component.literal(
                        NumberFormat.getPercentInstance()
                                .format(max > 0 ? (float) rem / max : 0F)));

        if (!flag.isAdvanced()) return;
        adder.accept(Component.translatable("desc.item.rtgPellet.extendedInfo"));
        adder.accept(Component.literal(String.format(Locale.US, "%s / %s ticks", rem, max)));
        adder.accept(
                Component.literal(
                        String.format(
                                Locale.US,
                                "Time remaining: %s y, %s d, %s h",
                                (Object[]) BobMathUtil.ticksToDate(rem))));
        adder.accept(
                Component.literal(
                        String.format(
                                Locale.US,
                                "Maximum life: %s y, %s d, %s h",
                                (Object[]) BobMathUtil.ticksToDate(max))));
    }

    private boolean SCALED() {
        return doesDecay && RTGUtil.SCALE_POWER;
    }

    @Override
    public InteractionResult use(Level level, Player player, InteractionHand hand) {
        if (!level.isClientSide() && this == ModItems.PELLET_RTG.get()) {
            player.sendSystemMessage(
                    Component.literal(FACTS[level.getRandom().nextInt(FACTS.length)])
                            .withStyle(ChatFormatting.YELLOW));
            level.playSound(
                    null,
                    player.getX(),
                    player.getY(),
                    player.getZ(),
                    SoundEvents.EXPERIENCE_ORB_PICKUP,
                    SoundSource.PLAYERS,
                    1.0F,
                    1.0F);
        }
        return InteractionResult.SUCCESS;
    }
}
